// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqTJnS1YQUifpwoXGCUq_KgPAweGUobtU',
    appId: '1:575967435374:web:1a6eea72da2a57fdf0647f',
    messagingSenderId: '575967435374',
    projectId: 'travellers-triibe',
    authDomain: 'travellers-triibe.firebaseapp.com',
    storageBucket: 'travellers-triibe.firebasestorage.app',
    measurementId: 'G-SC340F4QQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyXef02MmDZpoTwK-GTo9tQ6nENxqVhdg',
    appId: '1:575967435374:android:e2934909039fca6ff0647f',
    messagingSenderId: '575967435374',
    projectId: 'travellers-triibe',
    storageBucket: 'travellers-triibe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPtyuxX8ksbltIvaREGedU_o1SxRn2WjU',
    appId: '1:575967435374:ios:9c65aed65efbc018f0647f',
    messagingSenderId: '575967435374',
    projectId: 'travellers-triibe',
    storageBucket: 'travellers-triibe.firebasestorage.app',
    androidClientId: '575967435374-4durotqi15cj488c5m84uf27mpmbo9v7.apps.googleusercontent.com',
    iosClientId: '575967435374-ukcuq9n5r36914qd5cejfnjnel0mahnc.apps.googleusercontent.com',
    iosBundleId: 'com.travellerstriibe.travellersTriibe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPtyuxX8ksbltIvaREGedU_o1SxRn2WjU',
    appId: '1:575967435374:ios:9c65aed65efbc018f0647f',
    messagingSenderId: '575967435374',
    projectId: 'travellers-triibe',
    storageBucket: 'travellers-triibe.firebasestorage.app',
    androidClientId: '575967435374-4durotqi15cj488c5m84uf27mpmbo9v7.apps.googleusercontent.com',
    iosClientId: '575967435374-ukcuq9n5r36914qd5cejfnjnel0mahnc.apps.googleusercontent.com',
    iosBundleId: 'com.travellerstriibe.travellersTriibe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqTJnS1YQUifpwoXGCUq_KgPAweGUobtU',
    appId: '1:575967435374:web:586d5d72c6963683f0647f',
    messagingSenderId: '575967435374',
    projectId: 'travellers-triibe',
    authDomain: 'travellers-triibe.firebaseapp.com',
    storageBucket: 'travellers-triibe.firebasestorage.app',
    measurementId: 'G-D2CRSFRD12',
  );

}